In [1]:
import numpy as np
Population=5


In [2]:
import numpy as np
InitialInfected=3

In [3]:

SimulationDuration = 120  # assume rates in days
MaxNumEvents = 10000
MaxRuns = 200
RecoveryPeriod = 5  # 5 days to recover
InitialInfected = 3

In [4]:
R0 = 2
Beta = R0 / RecoveryPeriod
Gamma = 1. / RecoveryPeriod
outb = 0
rec = 0
peak = 0
EndTime: int = 0

In [5]:
Adj = np.random.randint (2, size = (Population,Population))  # creates random adjaceny matrix
Adj   

array([[0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [1, 0, 1, 0, 0]])

In [6]:
Adj = Adj.T * Adj # Creates Symmetric Matrix => not uni directional relationship 
Adj

array([[0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0]])

In [7]:
Nodes = np.zeros(Population)
        
    #Initial conditions
Infected=[InitialInfected]
Susceptible=[Population-InitialInfected]
Recovered=[0]
Times =[0]

Nodes[0:InitialInfected].fill(2) #Set initial Infected



In [8]:
Nodes    

array([2., 2., 2., 0., 0.])

In [9]:

Nodes[np.where(Nodes==0)]=1 # If Infected Updated Susceptible Flag
Nodes=Nodes.astype(int)
np.random.shuffle(Nodes) # shuffle infected nodes


SimTime = Times[0]
NumEvents = 0
Nodes

array([2, 1, 1, 2, 2])

In [10]:
Rate1 = Beta*Adj.dot(Nodes==2)*(Nodes==1)
Rate1


array([0. , 0.4, 0.8, 0. , 0. ])

In [11]:
(Nodes==2)

array([ True, False, False,  True,  True])

In [12]:
Rate2 = Gamma * (Nodes==2)
Rate2

array([0.2, 0. , 0. , 0.2, 0.2])

In [13]:
Adj

array([[0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0]])

In [14]:
Nodes

array([2, 1, 1, 2, 2])

In [15]:
Beta

0.4

In [16]:
        TotalRate = [Rate1, Rate2]


In [17]:
TotalRate

[array([0. , 0.4, 0.8, 0. , 0. ]), array([0.2, 0. , 0. , 0.2, 0.2])]

In [18]:
Rate1
Rate2

array([0.2, 0. , 0. , 0.2, 0.2])

In [19]:
Rate2

array([0.2, 0. , 0. , 0.2, 0.2])

In [20]:
Rate1

array([0. , 0.4, 0.8, 0. , 0. ])

In [21]:
c=[Rate1,Rate2]
c

[array([0. , 0.4, 0.8, 0. , 0. ]), array([0.2, 0. , 0. , 0.2, 0.2])]

In [22]:
np.concatenate((Rate1, Rate2))


array([0. , 0.4, 0.8, 0. , 0. , 0.2, 0. , 0. , 0.2, 0.2])

In [23]:
Alpha0=sum(Rate1)+sum(Rate2)
Alpha0

1.8000000000000003

In [24]:
import random


In [25]:
SelectEvent = random.random()
SelectEvent


0.2863490413669947

In [26]:
d=np.cumsum(np.concatenate((Rate1, Rate2)))/Alpha0
d

array([0.        , 0.22222222, 0.66666667, 0.66666667, 0.66666667,
       0.77777778, 0.77777778, 0.77777778, 0.88888889, 1.        ])

In [27]:
SelectEvent = random.random()
SelectEvent


0.32869442533609994

In [28]:
EventId=d.searchsorted(SelectEvent)

In [29]:
Reaction=EventId // Population
Node = (EventId % Population)

In [30]:
Reaction

0

In [31]:
Node

2

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import random

#
# Stocahastic SIR model
#
# Deterministic
# 2 - 80 - 79
# 3 - 94  - 94
# 4 - 98.6 - 98 Test dfdsf


SimulationDuration = 120  # assume rates in days
MaxNumEvents = 10000
MaxRuns = 200
RecoveryPeriod = 5  # 5 days to recover
InitialInfected = 3

# Scenarios  - #Dictionary of scenarios, population, country name, Ro, RecoveryPeriod

scenarios = [{"Country": "Scotland", "Population": 100, "R0": 2, "RecoveryPeriod": 5}]
            

In [33]:
for scenario in scenarios:

    Population = scenario["Population"]
    Country = scenario["Country"]
    RecoveryPeriod = scenario["RecoveryPeriod"]
    R0 = scenario["R0"]
    Beta = R0 / RecoveryPeriod
    Gamma = 1. / RecoveryPeriod
    InitialInfected = 1
    outb = 0
    rec = 0
    peak = 0
    EndTime: int = 0

    print("Scenario- Country", Country, "Beta ", Beta, "Gamma ", Gamma)

    Adj = np.random.randint (2, size = (Population,Population))  # creates random adjaceny matrix
    Adj = Adj.T * Adj # Creates Symmetric Matrix => not uni directional relationship    for run in range(1, MaxRuns):
        # Zero Arrays



Scenario- Country Scotland Beta  0.4 Gamma  0.2


In [34]:
    Nodes = np.zeros(Population)
        
    #Initial conditions
    Infected=[InitialInfected]
    Susceptible=[Population-InitialInfected]
    Recovered=[0]
    Times =[0]
    
    Nodes[0:InitialInfected-1].fill(2) #Set initial Infected
    
    Nodes[np.where(Nodes==0)]=1 # If Infected Updated Susceptible Flag
    Nodes=Nodes.astype(int)
    np.random.shuffle(Nodes) # shuffle infected nodes
    
    
    SimTime = Times[0]
    NumEvents = 0

In [35]:
InitialInfected

1

In [36]:
Adj

array([[0, 1, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 0]])

In [37]:
(Nodes==1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
(Nodes==2)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [37]:
while (SimTime < SimulationDuration and NumEvents < MaxNumEvents and Infected[NumEvents] > 0):

        Rate1 = Beta*Adj.dot(Nodes==2)*(Nodes==1)/Population

        Rate2 = Gamma * (Nodes==2)


KeyboardInterrupt: 

In [ ]:
Rate1

In [ ]:
Beta

In [ ]:
Nodes

In [ ]:
Beta

In [22]:
Infected[0]

3