In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random

#
# Stocahastic SIR model
#
# Deterministic
# 2 - 80 - 79
# 3 - 94  - 94
# 4 - 98.6 - 98 Test dfdsf


SimulationDuration = 120  # assume rates in days
MaxNumEvents = 10000
MaxRuns = 200
RecoveryPeriod = 5  # 5 days to recover
InitialInfected = 3

# Scenarios  - #Dictionary of scenarios, population, country name, Ro, RecoveryPeriod
            

In [2]:
Population = 100
Country = "scotland"
RecoveryPeriod = 5.
R0 = 2
Beta = R0 / RecoveryPeriod
Gamma = 1. / RecoveryPeriod
InitialInfected = 1
outb = 0
rec = 0
peak = 0
EndTime: int = 0

print("Scenario- Country", Country, "Beta ", Beta, "Gamma ", Gamma)

Adj = np.random.randint (2, size = (Population,Population))  # creates random adjaceny matrix
Adj = Adj.T * Adj # Creates Symmetric Matrix => not uni directional relationship    for run in range(1, MaxRuns):
        # Zero Arrays



Scenario- Country scotland Beta  0.4 Gamma  0.2


In [3]:
Nodes = np.zeros(Population)
        
    #Initial conditions
Infected=[InitialInfected]
Susceptible=[Population-InitialInfected]
Recovered=[0]
Times =[0]
    
Nodes[0:InitialInfected].fill(2) #Set initial Infected
InitialInfected
    
    

1

In [4]:
Nodes

array([2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
InitialInfected

1

In [6]:
Nodes

array([2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
Nodes[np.where(Nodes==0)]=1 # If Infected Updated Susceptible Flag
Nodes=Nodes.astype(int)
np.random.shuffle(Nodes) # shuffle infected nodes
    
    
SimTime = Times[0]
NumEvents = 0

In [8]:
Nodes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
Adj

array([[1, 1, 0, ..., 1, 1, 0],
       [1, 1, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 1, ..., 1, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 1]])

In [10]:
(Nodes==1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [11]:
(Nodes==2)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [12]:
Rate1

NameError: name 'Rate1' is not defined

In [13]:
Beta

0.4

In [14]:
Nodes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
Beta

0.4

In [16]:
Infected[0]

1