In [90]:
import numpy as np
import matplotlib.pyplot as plt
import random
import pandas as pd
import networkx as nx
InitialInfected=5

Population=10
Adj = np.random.randint (2, size = (Population,Population))  # creates random adjaceny matrix
Adj = Adj.T * Adj 
Adj.fill(1) # set connections between all
beta=0.2    
Nodes = np.zeros(Population)

In [91]:
Nodes[0:InitialInfected].fill(2) #Set initial Infected
Nodes[np.where(Nodes==0)]=1 # If Infected Updated Susceptible Flag
Nodes=Nodes.astype(int)
np.random.shuffle(Nodes) # shuffle infected nodes

In [92]:
G = nx.Graph()

In [93]:
Adj = np.random.randint (2, size = (Population,Population))  # creates random adjaceny matrix
Adj = Adj.T * Adj # C

In [94]:
Low=4
Medium=10
High=20

LowProp = .3
MedProp = .50
HighProp = .2

LowNum = int(Population*LowProp)
MedNum = int(Population*MedProp)
HighNum = int(Population*HighProp)

configmatrix=[Low]*LowNum + [Medium]*MedNum + [High]*HighNum
configmatrix

[4, 4, 4, 10, 10, 10, 10, 10, 20, 20]

In [95]:
cm=np.array(configmatrix)
np.random.shuffle(cm)

G=nx.configuration_model(cm) # Create graph from configuration model
G=nx.Graph(G)
G.number_of_nodes()

10

In [103]:
Adj2 = nx.to_numpy_array(G) #Generates Adjaceny matrix from graph
Adj2

array([[0., 1., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1., 0., 0., 1., 0., 0.],
       [1., 1., 1., 0., 1., 1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 1., 0.],
       [1., 1., 1., 0., 1., 1., 1., 1., 0., 1.],
       [0., 0., 1., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 0., 0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 1., 0., 0.]])

In [104]:
Beta=0.2

In [106]:
Rate1 = Beta*Adj2.dot(Nodes==2)*(Nodes==1)/Population

In [99]:
Rate1

array([0.  , 0.06, 0.02, 0.02, 0.02, 0.  , 0.  , 0.04, 0.  , 0.  ])

In [100]:
Adj

array([[0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]])

In [101]:
Adj2

matrix([[0., 1., 1., 0., 1., 0., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 0., 1., 0., 0.],
        [1., 1., 1., 0., 1., 1., 0., 1., 0., 1.],
        [0., 1., 0., 0., 0., 1., 0., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 1., 0., 1.],
        [0., 0., 1., 1., 1., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
        [0., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
        [1., 0., 0., 1., 0., 1., 0., 1., 0., 0.],
        [1., 0., 1., 0., 1., 0., 1., 1., 0., 0.]])